### ISSUE TITLE
docker 起動時に init.sh でエラーが発生

### ISSUE THREAD

**Issue by Yocote0111** [cstmatsulab/dcase_com#1]
```
$ docker run -it --rm -p 80:80 -v ${PWD}:/data dcase_com
/init.sh: line 2: $'\r': command not found
/init.sh: line 4: $'\r': command not found
Usage: /etc/init.d/php-fpm7.4 {start|stop|status|restart|reload|force-reload}
Usage: /etc/init.d/supervisord {start|stop|restart|force-reload|status}
/init.sh: line 7: $'\r': command not found
```

[init.sh](https://github.com/cstmatsulab/dcase_com/blob/1c602bfac850037eae41d85f3ee395abb24a3fa7/docker/init.sh) の改行コードがCRLF (Windows用) になっていることが原因と思われる. LF にしたらエラーが発生しなくなった.

**Comment by d-case** [comment]
おそくなってすいません、
githubに上がっているものを確認しましたが、LFになっていました。

https://www.matsulab.org/dcase/dl.html

また、上記サイトに最新版がありますので、dowload zipをダウンロードして、ご確認していただけたら幸いです。

また、ご指摘の箇所とは異なりますが、
dockerコンテナのビルドを試しているときに
readmeなどに一部、誤記があったので、
修正しました。

**Comment by Yocote0111** [comment]
すみません. 恐らく, git 側の問題ですね.  Windows の git で pull する際に LF が CRLF 自動変換されるような設定がデフォルトになっているようで..
この設定を変更したら問題なく動きました.

**Comment by d-case** [comment]
ご連絡ありがとうございます。よかったです。
